apiVersion: v2
name: dagster
description: Dagster is a system for building modern data applications.
type: application
version: 0.1.0
appVersion: 0.6.6
dependencies:
  - name: postgresql
    version: 8.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: celery.enabled
  # - name: nginx-ingress
  #   version: 0.27.1
  #   repository: https://kubernetes-charts.storage.googleapis.com/
  #   condition: nginx.enabled
