replicaCount: 1

imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

rbacEnabled: true

dagit:
  image: "dagster-docker-buildkite:latest"
  nameOverride: ""

# Image to use for executing jobs; this is typically the same image as dagit
job_image: "dagster-docker-buildkite:latest"

workers:
  nameOverride: ""

# Configuration values for postgresql
# https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  enabled: true
  postgresqlUsername: test
  # Note when changing this password (e.g. in test) that credentials will
  # persist as long as the PVCs do -- see:
  # https://github.com/helm/charts/issues/12836#issuecomment-524552358
  postgresqlPassword: test
  postgresqlDatabase: test
  service:
    port: 5432

# https://github.com/helm/charts/issues/17250#issuecomment-533444837
rabbitmq:
  volumePermissions:
    enabled: true

# Configuration values for rabbitmq and celery
celery:
  enabled: true
  service:
    port: 5672
  replicaCount: 5

# Configuration values for nginx-ingress
# nginx:
#   enabled: true

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
